sudo: required
dist: trusty
language: node_js
node_js: stable

notifications:
  email: false
  
cache:
  directories: node_modules


install:
- npm prune
- npm install
- npm run build

deploy:
  - provider: s3
    access_key_id: ${ARTIFACTS_KEY}
    secret_access_key: ${ARTIFACTS_SECRET}
    bucket: "webrepo.ustocktrade.com"
    skip_cleanup: true
    upload-dir: web_core
    local_dir: dist
